In [1]:
import random

In [ ]:
import numpy

ModuleNotFoundError: No module named 'numpy1'

In [3]:
%pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
!py -m pip install numpy 

In [4]:
import numpy

In [5]:
import numpy as np

print(np.__version__)

2.0.1


In [6]:
alist = [1,2,3,4,5,6,7]

In [8]:
print(type(alist))

<class 'list'>


In [9]:
alist

[1, 2, 3, 4, 5, 6, 7]

In [10]:
ar1 = np.array(alist)

In [12]:
print(type(ar1))
print(ar1)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


In [13]:
ar1

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
ar1.dtype

dtype('int64')

In [15]:
list_data = [1, 2.0, 3]

ar2 = np.array(list_data)
print(ar2)
print(ar2.dtype)

[1. 2. 3.]
float64


In [16]:
ar1.ndim

1

In [ ]:
ar1.shape # (7)

(7,)

In [18]:
ar3 = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])

In [19]:
print(ar3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
print(ar3.ndim)

2


In [21]:
print(ar3.shape)

(3, 4)


In [28]:
ar4 = ar3.reshape(2, -1)

In [29]:
print(ar4)
print(ar4.ndim)
print(ar4.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2
(2, 6)


In [31]:
ar3.reshape(2, 5)

ValueError: cannot reshape array of size 12 into shape (2,5)

In [35]:
ar5 = ar3.reshape(3, -1, 2)

In [36]:
print(ar5)
print(ar5.ndim)
print(ar5.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
(3, 2, 2)


In [41]:
x = np.arange(1, 6)
y = np.arange(6, 11)

In [42]:
x + y 

array([ 7,  9, 11, 13, 15])

In [39]:
alist = [1, 2, 3, 4, 5]
blist = [6, 7, 8, 9, 10]
alist + blist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
x = np.arange(1, 6)
y = np.arange(6, 11)

In [43]:
print(x + y )
print(x - y )
print(x * y )
print(x / y )

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [44]:
print(x + 1 )
print(x - 1 )
print(x * 2 )
print(x / 2 )

[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [46]:
L = range(1000)
%timeit L2 = [i**2 for i in L]

63.7 μs ± 5 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [47]:
arr = np.arange(1000)
%timeit arr2 = arr ** 2

1.48 μs ± 157 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [48]:
x == 1 

array([ True, False, False, False, False])

In [49]:
a = [[0, 1, 2], [3, 4, 5]]

In [54]:
# 0, 1, 5 인덱싱으로 뽑아주세요
a[0][0], a[0][1], a[-1][-1]

(0, 1, 5)

In [60]:
a[0,0], a[0, 1], a[-1, -1]

TypeError: list indices must be integers or slices, not tuple

In [55]:
b = np.array([[0, 1, 2], [3, 4, 5]])

In [56]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
print(b[0,0], b[0, 1], b[-1, -1])

0 1 5


In [58]:
print(b[0][0], b[0][1], b[-1][-1])

0 1 5


In [62]:
c = np.array([[0,1,2,3], [4,5,6,7]])
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [73]:
# [0, 1, 2], [1, 5]
print(c[0,:3], c[:, 1])
print(c[:, :2])

[0 1 2] [1 5]
[[0 1]
 [4 5]]


In [70]:
c[0, 1]

np.int64(1)

In [77]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([False, False, True, False, True, False, True, False, True, False])
a[idx]

array([2, 4, 6, 8])

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])